name: hello_workers
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  serverpod_serialization: ^2.4.0
  serverpod_shared: ^2.4.0
  serverpod:
    path: packages/serverpod_web
  postgres: ^3.0.1

dependency_overrides:
  postgres:
    path: packages/postgres