name: serverpod
version: 2.4.0
description: Serverpod is an open-source, scalable app server, written in Dart for the Flutter community.

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  args: ^2.4.0
  collection: ^1.17.1
  crypto: ^3.0.2
  http: '>=1.0.0 <2.0.0'
  meta: ^1.8.0
  mustache_template: ^2.0.0
  path: ^1.8.2
  postgres: ^3.0.1
  redis: ^4.0.0
  retry: ^3.1.1
  synchronized: ^3.1.0
  system_resources: ^1.6.0
  vm_service: ">=13.0.0 <16.0.0"
  yaml: ^3.1.1
  serverpod_shared: 2.4.0
  serverpod_serialization: 2.4.0
  uuid: ^4.1.0

dev_dependencies:
  test: ^1.24.2
  serverpod_lints: 2.4.0